services:
    web:
        image: nginx
        volumes:
            - ./nginx/new_conf.d:/etc/nginx/conf.d
            - ./:/etc/nginx/templates/app
            - ./build:/etc/nginx/templates/app/build
            - ./src:/etc/nginx/templates/app/src
            - ../README.md:/etc/nginx/templates/app/README2.md
        ports:
            - "80:80"
            - "443:443"
            # - "7002:80"
            # - "5500:80"
        environment:
            - NGINX_HOST=foobar.com
            - NGINX_PORT=80=
        networks:
            - mynetwork

networks:
  mynetwork:
    external: true